# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Branch hacer build'
        # Default value if no value is explicitly provided
        default: 'develop'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3    
    - run: |
        date > generated.txt
        git status
    - name: Echo branch    
      run: echo "Hello ${{ github.event.inputs.branch }}"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install pylint
        
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
      
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # LOGIN
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to hub
      run: |
        docker build -t arkon_dev .
        docker tag arkon_dev lmartinez/arkon:${{ github.event.inputs.branch }}
        docker push lmartinezs/arkon:${{ github.event.inputs.branch }}
        
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.branch }}"
